# Generated by Django 4.2 on 2023-04-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_api', '0003_alter_dog_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='photo',
        ),
        migrations.AddField(
            model_name='dog',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
